import React, {useEffect} from 'react';
import { useRouter } from 'next/router';

import Head from 'next/head'

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    router.push('/admin/dashboard');
  }, [router])

  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container'>
        <p>Hello Times</p>
      </div>
    </React.Fragment>
  )
}
